context.modules = [
    { name = libpipewire-module-loopback
        args = {
            node.description = "Game"
            capture.props = {
                node.name      = "game_output"
                media.class    = "Audio/Sink"
                audio.position = [ FL FR ]
                object.register = true
            }
            playback.props = {
                node.name      = "playback.game_output"
                audio.position = [ FL FR ]
                node.passive   = true
            }
        }
    }
    { name = libpipewire-module-loopback
        args = {
            node.description = "Voice"
            capture.props = {
                node.name      = "voice_output"
                media.class    = "Audio/Sink"
                audio.position = [ FL FR ]
                object.register = true
            }
            playback.props = {
                node.name      = "playback.voice_output"
                audio.position = [ FL FR ]
                node.passive   = true
            }
        }
    }
    { name = libpipewire-module-loopback
        args = {
            node.description = "Browser"
            capture.props = {
                node.name      = "browser_output"
                media.class    = "Audio/Sink"
                audio.position = [ FL FR ]
                object.register = true
            }
            playback.props = {
                node.name      = "playback.browser_output"
                audio.position = [ FL FR ]
                node.passive   = true
            }
        }
    }
    { name = libpipewire-module-loopback
        args = {
            node.description = "Music"
            capture.props = {
                node.name      = "music_output"
                media.class    = "Audio/Sink"
                audio.position = [ FL FR ]
                object.register = true
            }
            playback.props = {
                node.name      = "playback.music_output"
                audio.position = [ FL FR ]
                node.passive   = true
            }
        }
    }
]
